spring:
  datasource:
    url: jdbc:postgresql://ep-tight-butterfly-a2dw3k9k.eu-central-1.aws.neon.tech/strzelnica_db?sslmode=require
    username: strzelnica_db_owner
    password: uUE9AX5MeiNh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: false
        ddl-auto: none